- name: Hello World Sample
  hosts: all
  become: yes
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: install some packages
      yum:
        name:
          - sysstat
          - wget
          - unzip
          - git
        state: present
