- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Hello Variable
      debug:
        msg: "Variable1 is: {{ vm1-ip }}, Variable2 is: {{ vm1-hostname }}, Variable3 is: {{ vm2-ip }}, Variable4 is: {{ vm2-hostname }}"

