---
- name: Ensure that all packages are updated
  tags: yum-update
  become: true
  yum:
    conf_file: "{{ yum_update_conf_file|default(omit) }}"
    disable_gpg_check: "{{ yum_update_disable_gpg_check }}"
    disablerepo: "{{ yum_update_disablerepo|join(',') }}"
    enablerepo: "{{ yum_update_enablerepo|join(',') }}"
    exclude: "{{ yum_update_exclude }}"
    name: '*'
    state: latest
    update_cache: "{{ yum_update_update_cache }}"
    validate_certs: "{{ yum_update_validate_certs }}"
  register: yum_update
  when:
    - yum_update is defined
    - yum_update

- name: Gathering facts after package updates
  tags: yum-update
  action: setup
  when: yum_update|changed

- name: Adding and removing additional packages
  tags: yum-update
  become: true
  yum:
    conf_file: "{{ yum_update_conf_file|default(omit) }}"
    disable_gpg_check: "{{ yum_update_disable_gpg_check }}"
    disablerepo: "{{ yum_update_disablerepo|join(',') }}"
    enablerepo: "{{ yum_update_enablerepo|join(',') }}"
    name: "{{ item.package }}"
    state: "{{ item.state }}"
    validate_certs: "{{ yum_update_validate_certs }}"
  with_items: "{{ yum_update_perms }}"
  when:
    - item.package is defined
    - item.state is defined

- name: Applying directory and file permissions
  tags: yum-update
  become: true
  file:
    path: "{{ item.1.path }}"
    mode: "{{ item.1.mode }}"
  with_subelements:
    - "{{ yum_update_perms }}"
    - permissions
  when:
    - item.1.path is defined
    - item.1.mode is defined
...
