---
- set_fact:
    KUBE_CNI_BIN_PATH: "/opt/cni/bin"
    KUBE_CNI_CONF_PATH: "/etc/cni/net.d"

- name: create cni bin dir
  file: 
    path: "{{KUBE_CNI_BIN_PATH}}"
    recurse: yes
    state: directory

- name: create cni conf dir
  file: 
    path: "{{KUBE_CNI_CONF_PATH}}"
    recurse: yes
    state: directory

- name: copy 10-flannel.conf to cni conf dir
  copy:
    src: 10-flannel.conf
    dest: "{{KUBE_CNI_CONF_PATH}}/10-flannel.conf"
    owner: root
    group: root
    mode: 0644

- name: get cni plugin
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
    dest: /tmp/cni-plugins-amd64-v0.6.0.tgz

- name: copy to target and unarchive
  unarchive: 
    src: /tmp/cni-plugins-amd64-v0.6.0.tgz
    dest: "{{KUBE_CNI_BIN_PATH}}"

- name: Delete install file
  file:
    path: /tmp/cni-plugins-amd64-v0.6.0.tgz
    state: absent
