---
- set_fact:
    KUBE_CNI_BIN_PATH: "/opt/cni/bin"
    KUBE_CNI_CONF_PATH: "/etc/cni/net.d"

- name: create cni bin dir
  file: 
    path: "{{KUBE_CNI_BIN_PATH}}"
    recurse: yes
    state: directory

- name: create cni conf dir
  file: 
    path: "{{KUBE_CNI_CONF_PATH}}"
    recurse: yes
    state: directory

- name: copy 10-flannel.conf to cni conf dir
  copy:
    dest: "{{KUBE_CNI_CONF_PATH}}/10-flannel.conf"
    owner: root
    group: root
    mode: 0644
    content: |
        {
            "name": "cbr0",
            "type": "flannel",
            "delegate": {
                "isDefaultGateway": true
            }
        }

#- name: get cni plugin
#  get_url:
#    url: https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
#    dest: /tmp/cni-plugins-amd64-v0.6.0.tgz
#    checksum: md5:9534876fae7dbe813cdab404dc1f9219

- name: copy to target and unarchive
  unarchive: 
    src: /tmp/cni-plugins-amd64-v0.6.0.tgz
    dest: "{{KUBE_CNI_BIN_PATH}}"

