---
dependencies: []
galaxy_info:
  author: tkimball83
  description: RHEL/CentOS - Package updates and permission settings
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 5
        - 6
        - 7
  galaxy_tags:
    - system
    - update
    - yum
...
