---
- name: install C compiler
  yum:
    name: gcc, openssl-devel, tar
    state: latest

# install keepalived
- name: delete directory
  file:
    path: "/tmp/keepalived-{{ keepalived_version }}"
    state: absent

- name: copy to target and unarchive
  unarchive: src="keepalived-{{ keepalived_version }}.tar.gz" dest=/tmp/

- name: run ./configure in keepalived
  command: "{{ item }}"
  args:
    chdir: "/tmp/keepalived-{{ keepalived_version }}/"
  with_items:
  - ./configure --prefix=/usr/local/keepalived

- name: make all in keepalived
  make:
    chdir: "/tmp/keepalived-{{ keepalived_version }}"
    target: all

- name: make install in keepalived
  make:
    chdir: "/tmp/keepalived-{{ keepalived_version }}"
    target: install
  become: yes

# redis
- name: delete directory
  file:
    path: "/tmp/redis-{{ redis_version }}"
    state: absent

- name: copy to target and unarchive
  unarchive: src="redis-{{ redis_version }}.tar.gz" dest=/tmp/

- name: make all in redis
  make:
    chdir: "/tmp/redis-{{ redis_version }}"
    target: all

- name: make install in redis
  make:
    chdir: "/tmp/redis-{{ redis_version }}"
    target: install
  become: yes

